In [2]:
import numpy as np
import pandas as pd
from numpy.ma.core import ceil
from scipy.spatial import distance #distance calculation
from sklearn.preprocessing import MinMaxScaler #normalisation
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score #scoring
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from matplotlib import animation, colors

from sklearn.preprocessing import StandardScaler
import os

# prepare the data

In [6]:
df = pd.read_csv("year2data.csv",index_col = 0)
df

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,0.329231,0.328000,0.326154,0.323692,0.321231,0.318769,0.316923,0.315077,0.312615,0.310154,...,0.339692,0.336615,0.336615,0.335385,0.336615,0.339077,0.341538,58.0,11.0,CL
1,0.139692,0.139077,0.137846,0.137231,0.137231,0.137231,0.137846,0.138462,0.140308,0.142154,...,0.084308,0.081231,0.080000,0.082462,0.086154,0.092308,0.102769,94.0,17.0,CL
2,0.475692,0.473846,0.471385,0.468923,0.465846,0.462769,0.460308,0.456615,0.453538,0.450462,...,0.422769,0.422154,0.423385,0.425846,0.429538,0.435077,0.443077,100.0,32.0,CL
3,0.248615,0.243692,0.240000,0.237538,0.235692,0.234462,0.234462,0.235692,0.237538,0.240615,...,0.216000,0.214154,0.216615,0.222769,0.232615,0.246154,0.264615,31.0,29.0,CL
4,0.248615,0.243692,0.240000,0.237538,0.235692,0.234462,0.234462,0.235692,0.237538,0.240615,...,0.216000,0.214154,0.216615,0.222769,0.232615,0.246154,0.264615,31.0,29.0,CL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,0.844923,0.857231,0.872615,0.886154,0.890462,0.892308,0.890462,0.887385,0.881846,0.872615,...,0.892308,0.889846,0.887385,0.889231,0.896000,0.899077,0.900308,91.0,53.0,NROI
737,0.912615,0.915692,0.923692,0.929846,0.932308,0.935385,0.936615,0.937231,0.937231,0.936615,...,0.932923,0.929846,0.927385,0.926154,0.926769,0.927385,0.928615,27.0,31.0,NROI
738,0.931077,0.933538,0.931692,0.931692,0.931077,0.929231,0.928615,0.926769,0.926769,0.929846,...,0.921231,0.920615,0.921846,0.921846,0.923077,0.920615,0.921846,28.0,37.0,NROI
739,0.868923,0.875077,0.880000,0.883692,0.884923,0.884923,0.883692,0.881231,0.878769,0.875077,...,0.877538,0.881846,0.887385,0.892923,0.898462,0.904000,0.913846,24.0,28.0,NROI
740,0.856000,0.864000,0.874462,0.876923,0.873846,0.864000,0.868923,0.872615,0.880615,0.889846,...,0.937231,0.937846,0.936615,0.935385,0.933538,0.931077,0.927385,24.0,27.0,NROI

# CL

In [48]:
path="../RawData/CESMZ200/2yearunnormlabeleddata/CL"
data = np.empty(shape=(1,225))
counter = 0
for filename in os.listdir(path):
    counter+=1
    f = os.path.join(path,filename)
    newdata = pd.read_csv(f, header = None).values.reshape((1,-1))
    data = np.concatenate((data,newdata))
    data_delete = np.delete(data,0,0)
    print(filename)

x=[]
y=[]
for i in range(1,179,1):
    x.append(int(df.iloc[i]['225']))
    y.append(int(df.iloc[i]['226']))
    
x_read = np.array(x)
x_read = x_read.reshape((1,-1))

y_read = np.array(y)
y_read = y_read.reshape((1,-1))

data_final = np.concatenate((data_delete, x_read.T,y_read.T), axis=1)
data_final_frame = pd.DataFrame(data_final)
data_final_frame['label'] = "CL"
data_final_frame.to_csv('cl2year_xy_unnormed.csv')
data_final_frame

Day100_c4_cp2_94_17.csv
Day116_c7_cp2_100_32.csv
Day120_c1_cp2_31_29.csv
Day120_c2_cp2_31_29.csv
Day121_c2_cp2_31_28.csv
Day125_c3_cp2_49_32.csv
Day127_c3_cp3_96_38.csv
Day127_c4_cp3_96_38.csv
Day128_c3_cp4_98_38.csv
Day128_c4_cp3_98_38.csv
Day133_c1_cp2_52_12.csv
Day134_c1_cp2_57_16.csv
Day134_c2_cp2_57_16.csv
Day135_c1_cp2_64_17.csv
Day135_c2_cp2_64_17.csv
Day136_c1_cp1_68_18.csv
Day159_c3_cp3_14_30.csv
Day164_c1_cp1_86_12.csv
Day166_c1_cp2_95_12.csv
Day16_c1_cp1_58_11.csv
Day174_c2_cp2_54_23.csv
Day176_c3_cp2_81_15.csv
Day179_c3_cp2_24_20.csv
Day17_c4_cp3_25_23.csv
Day180_c7_cp2_53_39.csv
Day183_c2_cp2_86_17.csv
Day184_c2_cp3_93_20.csv
Day189_c5_cp2_24_34.csv
Day191_c1_cp1_88_14.csv
Day192_c1_cp1_73_13.csv
Day193_c1_cp1_70_16.csv
Day194_c1_cp1_72_17.csv
Day195_c1_cp1_76_17.csv
Day198_c1_cp1_74_15.csv
Day199_c1_cp1_75_17.csv
Day200_c1_cp1_78_19.csv
Day201_c1_cp1_81_20.csv
Day201_c2_cp1_81_20.csv
Day202_c1_cp1_89_21.csv
Day203_c1_cp1_95_21.csv
Day219_c2_cp2_95_15.csv
Day228_c1_cp1_87_11.csv
Day252_c1_cp3_71_15.csv
Day254_c2_cp3_86_16.csv
Day255_c2_cp2_92_11.csv
Day258_c3_cp2_84_23.csv
Day259_c3_cp2_91_20.csv
Day260_c3_cp2_98_19.csv
Day307_c5_cp2_86_24.csv
Day308_c5_cp2_88_22.csv
Day309_c4_cp2_91_20.csv
Day312_c5_cp2_80_31.csv
Day313_c5_cp2_85_27.csv
Day329_c1_cp1_82_14.csv
Day330_c1_cp1_76_12.csv
Day336_c1_cp3_91_11.csv
Day349_c2_cp2_11_22.csv
Day350_c4_cp2_78_21.csv
Day351_c3_cp2_85_20.csv
Day356_c3_cp2_100_23.csv
Day359_c2_cp3_74_27.csv
Day360_c3_cp3_78_25.csv
Day361_c3_cp2_80_24.csv
Day362_c3_cp2_84_25.csv
Day363_c3_cp2_26_27.csv
Day367_c3_cp2_100_27.csv
Day371_c1_cp1_77_11.csv
Day373_c1_cp1_68_14.csv
Day37_c1_cp1_83_11.csv
Day381_c3_cp2_76_24.csv
Day385_c2_cp3_91_26.csv
Day386_c2_cp3_98_21.csv
Day387_c2_cp3_102_17.csv
Day38_c1_cp1_86_14.csv
Day393_c1_cp1_64_19.csv
Day394_c1_cp1_69_27.csv
Day396_c1_cp1_79_26.csv
Day397_c1_cp1_82_25.csv
Day398_c1_cp2_92_27.csv
Day41_c3_cp2_25_17.csv
Day42_c3_cp2_17_18.csv
Day432_c4_cp2_102_29.csv
Day433_c3_cp2_101_31.csv
Day433_c4_cp2_101_31.csv
Day433_c5_cp2_101_31.csv
Day43_c4_cp2_14_18.csv
Day443_c1_cp1_71_16.csv
Day444_c1_cp1_67_21.csv
Day445_c1_cp1_70_23.csv
Day447_c1_cp1_73_25.csv
Day448_c1_cp1_78_23.csv
Day449_c1_cp1_83_22.csv
Day450_c1_cp1_90_19.csv
Day450_c2_cp2_91_19.csv
Day451_c1_cp2_91_21.csv
Day451_c2_cp2_91_21.csv
Day454_c1_cp1_68_13.csv
Day454_c6_cp3_15_29.csv
Day455_c1_cp1_69_15.csv
Day456_c1_cp1_71_15.csv
Day457_c1_cp1_68_11.csv
Day470_c5_cp2_43_26.csv
Day477_c1_cp1_71_19.csv
Day478_c1_cp1_71_21.csv
Day480_c1_cp1_77_22.csv
Day480_c2_cp1_77_22.csv
Day481_c1_cp1_79_24.csv
Day481_c2_cp1_79_24.csv
Day482_c1_cp1_81_25.csv
Day482_c2_cp1_81_25.csv
Day483_c1_cp1_84_27.csv
Day483_c2_cp1_84_27.csv
Day484_c1_cp1_88_26.csv
Day485_c1_cp1_89_26.csv
Day486_c1_cp1_89_27.csv
Day487_c1_cp1_92_27.csv
Day487_c2_cp1_92_27.csv
Day488_c1_cp1_97_29.csv
Day488_c2_cp1_97_29.csv
Day489_c1_cp1_101_28.csv
Day497_c1_cp1_11_24.csv
Day499_c2_cp2_99_24.csv
Day503_c1_cp2_16_18.csv
Day506_c1_cp2_87_17.csv
Day506_c2_cp4_48_25.csv
Day507_c1_cp2_89_19.csv
Day508_c1_cp1_93_17.csv
Day509_c1_cp1_92_15.csv
Day510_c1_cp1_92_15.csv
Day511_c1_cp1_96_16.csv
Day512_c1_cp1_100_16.csv
Day515_c2_cp2_22_32.csv
Day519_c2_cp2_21_26.csv
Day521_c2_cp3_22_27.csv
Day527_c3_cp3_77_26.csv
Day528_c3_cp2_79_25.csv
Day529_c2_cp2_80_23.csv
Day530_c2_cp2_81_21.csv
Day531_c1_cp2_83_21.csv
Day532_c2_cp2_94_20.csv
Day541_c1_cp2_94_17.csv
Day542_c1_cp1_102_21.csv
Day546_c1_cp1_84_16.csv
Day547_c1_cp2_85_21.csv
Day549_c1_cp1_96_18.csv
Day553_c1_cp2_88_21.csv
Day556_c1_cp2_84_20.csv
Day557_c1_cp2_93_21.csv
Day570_c1_cp1_92_15.csv
Day571_c1_cp2_96_17.csv
Day571_c2_cp1_11_12.csv
Day575_c2_cp2_102_18.csv
Day578_c2_cp2_93_21.csv
Day595_c2_cp2_99_16.csv
Day606_c8_cp2_43_40.csv
Day607_c3_cp2_93_19.csv
Day610_c2_cp2_83_13.csv
Day611_c1_cp2_82_16.csv
Day612_c1_cp2_80_18.csv
Day613_c2_cp2_84_19.csv
Day616_c1_cp2_11_20.csv
Day636_c3_cp2_11_20.csv
Day651_c5_cp2_42_26.csv
Day655_c1_cp3_18_16.csv
Day656_c2_cp2_16_12.csv
Day656_c3_cp2_102_16.csv
Day658_c2_cp3_91_18.csv
Day665_c2_cp2_88_13.csv
Day680_c1_cp3_80_12.csv
Day692_c2_cp2_100_18.csv
Day696_c4_cp2_102_17.csv
Day722_c2_cp2_87_14.csv
Day723_c2_cp3_87_15.csv
Day90_c1_cp1_77_11.csv
Day94_c1_cp1_69_13.csv
Day95_c1_cp2_77_16.csv
Day96_c1_cp2_82_17.csv
Day99_c2_cp2_93_20.csv

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11043.0,11038.0,11036.0,11040.0,11046.0,11056.0,11073.0,94.0,17.0,CL
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11593.0,11592.0,11594.0,11598.0,11604.0,11613.0,11626.0,100.0,32.0,CL
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11257.0,11254.0,11258.0,11268.0,11284.0,11306.0,11336.0,31.0,29.0,CL
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11257.0,11254.0,11258.0,11268.0,11284.0,11306.0,11336.0,31.0,29.0,CL
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11253.0,11253.0,11257.0,11266.0,11279.0,11296.0,11318.0,31.0,28.0,CL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,10781.0,10780.0,10779.0,10779.0,10779.0,10780.0,10781.0,10782.0,10784.0,10786.0,...,10724.0,10727.0,10733.0,10739.0,10747.0,10756.0,10767.0,77.0,11.0,CL
174,10873.0,10871.0,10869.0,10868.0,10866.0,10865.0,10864.0,10863.0,10863.0,10864.0,...,10911.0,10913.0,10917.0,10924.0,10933.0,10946.0,10960.0,69.0,13.0,CL
175,10965.0,10963.0,10961.0,10961.0,10961.0,10962.0,10964.0,10966.0,10969.0,10972.0,...,10927.0,10926.0,10928.0,10934.0,10943.0,10956.0,10972.0,77.0,16.0,CL
176,10972.0,10970.0,10969.0,10968.0,10968.0,10969.0,10970.0,10973.0,10976.0,10980.0,...,10932.0,10925.0,10922.0,10923.0,10929.0,10939.0,10953.0,82.0,17.0,CL
177,11168.0,11164.0,11160.0,11157.0,11154.0,11150.0,11146.0,11143.0,11142.0,11140.0,...,11033.0,11046.0,11061.0,11077.0,11094.0,11112.0,11132.0,93.0,20.0,CL

# COL

In [49]:
path="../RawData/CESMZ200/2yearunnormlabeleddata/COL"
data = np.empty(shape=(1,225))
counter = 0
for filename in os.listdir(path):
    counter+=1
    f = os.path.join(path,filename)
    newdata = pd.read_csv(f, header = None).values.reshape((1,-1))
    data = np.concatenate((data,newdata))
    data_delete = np.delete(data,0,0)
    print(filename)
    
x=[]
y=[]
for i in range(180,507,1):
    x.append(int(df.iloc[i]['225']))
    y.append(int(df.iloc[i]['226']))
print(x,y)

x_read = np.array(x)
x_read = x_read.reshape((1,-1))

y_read = np.array(y)
y_read = y_read.reshape((1,-1))

data_final = np.concatenate((data_delete, x_read.T,y_read.T), axis=1)
data_final_frame = pd.DataFrame(data_final)
data_final_frame['label'] = "COL"
data_final_frame.to_csv('col2year_xy_unnormed.csv')
data_final_frame

Day107_c8_cp2_33_40.csv
Day108_c8_cp2_36_38.csv
Day113_c9_cp2_98_37.csv
Day114_c9_cp2_100_41.csv
Day115_c8_cp2_102_38.csv
Day116_c11_cp2_41_58.csv
Day117_c11_cp2_42_58.csv
Day123_c1_cp3_38_29.csv
Day124_c2_cp3_43_32.csv
Day124_c3_cp2_84_33.csv
Day125_c3_cp3_90_38.csv
Day125_c4_cp2_90_37.csv
Day126_c3_cp4_93_38.csv
Day126_c4_cp2_93_38.csv
Day128_c4_cp4_67_39.csv
Day134_c9_cp2_12_57.csv
Day141_c5_cp4_60_33.csv
Day142_c3_cp2_97_34.csv
Day143_c3_cp2_100_35.csv
Day145_c3_cp2_33_32.csv
Day146_c5_cp2_81_39.csv
Day147_c5_cp2_82_38.csv
Day148_c4_cp3_35_38.csv
Day149_c3_cp3_33_39.csv
Day149_c4_cp2_33_39.csv
Day149_c5_cp2_33_39.csv
Day150_c3_cp2_32_38.csv
Day150_c4_cp2_32_38.csv
Day150_c5_cp2_32_38.csv
Day151_c3_cp2_31_37.csv
Day151_c4_cp2_31_37.csv
Day152_c3_cp2_13_40.csv
Day153_c3_cp2_16_43.csv
Day153_c4_cp3_16_43.csv
Day154_c3_cp2_17_42.csv
Day154_c4_cp3_17_42.csv
Day155_c3_cp4_18_37.csv
Day155_c4_cp5_18_37.csv
Day155_c5_cp2_18_37.csv
Day156_c3_cp5_13_32.csv
Day168_c3_cp2_98_27.csv
Day174_c8_cp3_33_59.csv
Day175_c8_cp3_12_53.csv
Day175_c8_cp4_32_58.csv
Day179_c8_cp2_31_53.csv
Day179_c9_cp2_31_53.csv
Day180_c7_cp3_31_51.csv
Day181_c7_cp4_33_47.csv
Day185_c9_cp2_80_62.csv
Day190_c4_cp2_28_32.csv
Day191_c4_cp3_28_32.csv
Day191_c5_cp3_28_32.csv
Day192_c5_cp4_29_33.csv
Day194_c4_cp3_14_32.csv
Day195_c4_cp2_12_32.csv
Day195_c5_cp2_12_32.csv
Day196_c3_cp3_12_31.csv
Day196_c4_cp2_12_31.csv
Day200_c4_cp2_25_35.csv
Day201_c5_cp2_28_36.csv
Day202_c5_cp2_25_35.csv
Day202_c6_cp2_25_35.csv
Day203_c5_cp2_24_36.csv
Day204_c4_cp2_27_33.csv
Day206_c5_cp2_42_29.csv
Day214_c5_cp2_39_30.csv
Day214_c7_cp2_12_47.csv
Day221_c4_cp3_99_25.csv
Day222_c6_cp3_40_31.csv
Day223_c6_cp2_41_30.csv
Day224_c6_cp2_25_32.csv
Day225_c6_cp2_27_31.csv
Day229_c6_cp2_74_38.csv
Day231_c7_cp2_44_30.csv
Day232_c7_cp2_46_31.csv
Day235_c6_cp2_85_25.csv
Day249_c4_cp2_88_21.csv
Day251_c8_cp2_86_52.csv
Day257_c2_cp2_78_23.csv
Day257_c3_cp2_78_23.csv
Day259_c7_cp2_49_33.csv
Day25_c11_cp2_59_48.csv
Day260_c7_cp2_50_32.csv
Day260_c8_cp2_50_32.csv
Day261_c8_cp2_51_30.csv
Day262_c8_cp2_58_29.csv
Day263_c8_cp2_62_28.csv
Day265_c11_cp2_75_49.csv
Day266_c11_cp2_73_49.csv
Day266_c12_cp2_73_49.csv
Day267_c11_cp2_73_49.csv
Day267_c8_cp2_45_42.csv
Day268_c11_cp2_72_47.csv
Day270_c9_cp2_48_45.csv
Day271_c12_cp2_92_52.csv
Day276_c10_cp2_40_43.csv
Day277_c10_cp2_41_42.csv
Day277_c11_cp2_41_42.csv
Day278_c10_cp2_42_38.csv
Day278_c7_cp2_21_37.csv
Day279_c10_cp2_50_43.csv
Day279_c7_cp2_25_35.csv
Day279_c8_cp2_25_35.csv
Day280_c10_cp2_52_44.csv
Day280_c7_cp2_27_31.csv
Day286_c9_cp2_71_41.csv
Day287_c10_cp2_72_42.csv
Day287_c6_cp2_27_35.csv
Day292_c12_cp2_43_46.csv
Day293_c12_cp2_42_47.csv
Day293_c13_cp2_42_47.csv
Day294_c12_cp2_42_48.csv
Day294_c13_cp2_42_48.csv
Day295_c11_cp2_67_44.csv
Day295_c12_cp2_43_49.csv
Day296_c12_cp2_46_48.csv
Day302_c13_cp2_48_54.csv
Day306_c6_cp2_78_25.csv
Day311_c6_cp2_74_35.csv
Day317_c9_cp2_25_44.csv
Day318_c9_cp2_26_39.csv
Day328_c12_cp2_35_53.csv
Day329_c12_cp2_33_56.csv
Day337_c10_cp2_51_47.csv
Day338_c10_cp2_56_47.csv
Day340_c3_cp2_88_27.csv
Day346_c11_cp2_97_51.csv
Day374_c2_cp3_83_31.csv
Day375_c2_cp3_90_26.csv
Day37_c9_cp2_22_28.csv
Day383_c3_cp2_75_24.csv
Day395_c1_cp1_75_28.csv
Day429_c12_cp2_16_53.csv
Day430_c12_cp2_15_54.csv
Day430_c13_cp2_15_54.csv
Day431_c12_cp2_15_54.csv
Day439_c9_cp2_12_39.csv
Day440_c8_cp2_14_37.csv
Day461_c7_cp2_74_32.csv
Day461_c8_cp2_74_32.csv
Day462_c8_cp2_78_32.csv
Day463_c15_cp2_11_59.csv
Day463_c8_cp2_83_34.csv
Day464_c6_cp2_87_34.csv
Day465_c5_cp2_88_31.csv
Day467_c14_cp2_24_60.csv
Day467_c6_cp2_92_32.csv
Day468_c13_cp2_29_59.csv
Day472_c12_cp2_70_57.csv
Day472_c6_cp2_43_32.csv
Day473_c6_cp3_48_34.csv
Day474_c6_cp3_24_36.csv
Day475_c4_cp2_22_35.csv
Day475_c5_cp2_22_35.csv
Day476_c4_cp2_22_39.csv
Day476_c5_cp2_22_39.csv
Day477_c5_cp2_21_40.csv
Day477_c6_cp3_21_40.csv
Day478_c5_cp2_21_40.csv
Day478_c6_cp3_21_40.csv
Day480_c12_cp2_95_51.csv
Day482_c11_cp2_59_50.csv
Day482_c5_cp3_20_31.csv
Day483_c5_cp4_26_29.csv
Day489_c9_cp2_53_53.csv
Day490_c9_cp2_55_53.csv
Day493_c2_cp2_87_28.csv
Day497_c3_cp3_86_27.csv
Day498_c2_cp2_96_30.csv
Day503_c5_cp2_99_45.csv
Day504_c4_cp2_102_47.csv
Day504_c5_cp2_102_47.csv
Day504_c6_cp2_102_47.csv
Day505_c2_cp3_45_20.csv
Day513_c3_cp2_34_29.csv
Day513_c8_cp2_88_51.csv
Day514_c8_cp2_90_52.csv
Day515_c8_cp2_94_50.csv
Day517_c2_cp2_18_30.csv
Day518_c2_cp2_22_27.csv
Day518_c7_cp2_62_44.csv
Day520_c1_cp2_101_24.csv
Day520_c2_cp2_20_27.csv
Day523_c2_cp2_12_30.csv
Day524_c2_cp2_12_29.csv
Day524_c3_cp2_12_29.csv
Day525_c3_cp2_13_26.csv
Day525_c7_cp2_45_48.csv
Day526_c3_cp2_73_24.csv
Day526_c7_cp2_46_48.csv
Day527_c7_cp2_44_46.csv
Day528_c7_cp2_42_47.csv
Day52_c7_cp2_97_33.csv
Day531_c2_cp2_42_26.csv
Day533_c3_cp2_32_30.csv
Day534_c4_cp2_33_32.csv
Day535_c4_cp2_37_32.csv
Day536_c9_cp2_100_59.csv
Day537_c9_cp2_100_58.csv
Day538_c9_cp2_100_55.csv
Day53_c7_cp2_100_32.csv
Day541_c5_cp2_44_33.csv
Day541_c7_cp2_93_48.csv
Day542_c6_cp2_45_33.csv
Day542_c8_cp2_92_49.csv
Day543_c5_cp2_45_33.csv
Day543_c8_cp2_91_50.csv
Day544_c5_cp2_41_34.csv
Day544_c8_cp3_91_49.csv
Day545_c5_cp2_39_34.csv
Day545_c8_cp3_91_49.csv
Day546_c5_cp2_36_34.csv
Day546_c8_cp3_92_47.csv
Day547_c5_cp2_33_35.csv
Day548_c8_cp1_35_18.csv
Day551_c6_cp2_46_36.csv
Day552_c6_cp2_45_35.csv
Day553_c6_cp2_39_36.csv
Day554_c6_cp2_37_37.csv
Day554_c9_cp2_89_63.csv
Day555_c6_cp2_37_38.csv
Day555_c9_cp4_87_61.csv
Day556_c6_cp2_38_36.csv
Day556_c9_cp2_85_59.csv
Day557_c9_cp2_85_58.csv
Day560_c3_cp2_90_27.csv
Day561_c7_cp2_23_41.csv
Day562_c10_cp2_99_56.csv
Day563_c10_cp3_96_56.csv
Day564_c10_cp3_93_57.csv
Day564_c9_cp2_93_57.csv
Day565_c10_cp2_91_57.csv
Day566_c10_cp2_88_56.csv
Day567_c9_cp2_84_55.csv
Day568_c5_cp2_34_30.csv
Day568_c9_cp2_81_54.csv
Day569_c9_cp4_78_53.csv
Day571_c9_cp2_92_55.csv
Day572_c2_cp2_98_17.csv
Day572_c9_cp2_88_56.csv
Day573_c8_cp2_20_53.csv
Day573_c9_cp2_85_57.csv
Day574_c7_cp2_14_52.csv
Day574_c8_cp3_82_58.csv
Day575_c7_cp2_13_51.csv
Day575_c8_cp3_75_62.csv
Day576_c7_cp2_40_45.csv
Day576_c8_cp2_74_63.csv
Day577_c8_cp3_82_59.csv
Day578_c8_cp3_80_61.csv
Day580_c2_cp4_97_25.csv
Day581_c5_cp2_33_38.csv
Day581_c8_cp2_78_63.csv
Day582_c9_cp3_76_62.csv
Day583_c9_cp5_67_57.csv
Day585_c8_cp4_98_60.csv
Day586_c8_cp3_95_60.csv
Day588_c8_cp2_65_55.csv
Day589_c8_cp2_65_57.csv
Day590_c8_cp2_76_58.csv
Day591_c7_cp2_99_55.csv
Day591_c8_cp2_72_58.csv
Day592_c8_cp2_70_58.csv
Day593_c8_cp2_70_57.csv
Day598_c3_cp2_78_23.csv
Day603_c6_cp2_87_36.csv
Day603_c9_cp3_55_53.csv
Day604_c9_cp2_54_53.csv
Day605_c10_cp2_55_54.csv
Day605_c2_cp2_80_12.csv
Day605_c7_cp2_47_28.csv
Day608_c2_cp2_98_23.csv
Day608_c3_cp2_98_23.csv
Day609_c9_cp2_69_60.csv
Day615_c9_cp2_12_53.csv
Day626_c2_cp2_99_23.csv
Day628_c10_cp2_40_49.csv
Day630_c8_cp2_65_41.csv
Day631_c8_cp2_67_42.csv
Day633_c5_cp2_12_29.csv
Day637_c9_cp2_37_42.csv
Day638_c9_cp2_43_44.csv
Day639_c9_cp2_46_45.csv
Day640_c9_cp2_19_46.csv
Day641_c11_cp2_17_49.csv
Day642_c11_cp2_17_48.csv
Day643_c10_cp2_39_52.csv
Day643_c11_cp2_39_52.csv
Day644_c10_cp2_43_49.csv
Day644_c12_cp2_97_61.csv
Day647_c8_cp2_26_43.csv
Day648_c12_cp2_72_56.csv
Day650_c11_cp2_100_52.csv
Day651_c11_cp2_98_52.csv
Day651_c13_cp3_14_61.csv
Day653_c12_cp2_36_58.csv
Day654_c11_cp2_35_54.csv
Day654_c11_cp3_101_62.csv
Day655_c9_cp2_70_50.csv
Day656_c10_cp2_70_53.csv
Day661_c8_cp2_42_48.csv
Day662_c10_cp2_42_48.csv
Day663_c10_cp2_43_45.csv
Day663_c9_cp2_43_45.csv
Day664_c9_cp2_47_41.csv
Day668_c5_cp2_22_25.csv
Day669_c4_cp2_27_24.csv
Day670_c10_cp2_65_41.csv
Day671_c10_cp2_66_40.csv
Day671_c12_cp2_89_57.csv
Day672_c13_cp2_88_57.csv
Day672_c5_cp2_48_23.csv
Day673_c13_cp2_89_59.csv
Day675_c14_cp2_91_61.csv
Day68_c14_cp2_27_55.csv
Day68_c15_cp2_27_55.csv
Day695_c9_cp2_38_38.csv
Day696_c10_cp2_42_40.csv
Day69_c13_cp2_28_57.csv
Day700_c10_cp2_51_41.csv
Day71_c13_cp2_27_49.csv
Day72_c13_cp2_24_49.csv
Day72_c14_cp2_24_49.csv
Day73_c13_cp2_25_49.csv
Day84_c15_cp2_48_56.csv
Day95_c8_cp2_18_39.csv
Day96_c8_cp2_18_40.csv
[33, 36, 98, 100, 102, 41, 42, 38, 43, 84, 90, 90, 93, 93, 67, 12, 60, 97, 100, 33, 81, 82, 35, 33, 33, 33, 32, 32, 32, 31, 31, 13, 16, 16, 17, 17, 18, 18, 18, 13, 98, 33, 12, 32, 31, 31, 31, 33, 80, 28, 28, 28, 29, 14, 12, 12, 12, 12, 25, 28, 25, 25, 24, 27, 42, 39, 12, 99, 40, 41, 25, 27, 74, 44, 46, 85, 88, 86, 78, 78, 49, 59, 50, 50, 51, 58, 62, 75, 73, 73, 73, 45, 72, 48, 92, 40, 41, 41, 42, 21, 50, 25, 25, 52, 27, 71, 72, 27, 43, 42, 42, 42, 42, 67, 43, 46, 48, 78, 74, 25, 26, 35, 33, 51, 56, 88, 97, 83, 90, 22, 75, 75, 16, 15, 15, 15, 12, 14, 74, 74, 78, 11, 83, 87, 88, 24, 92, 29, 70, 43, 48, 24, 22, 22, 22, 22, 21, 21, 21, 21, 95, 59, 20, 26, 53, 55, 87, 86, 96, 99, 102, 102, 102, 45, 34, 88, 90, 94, 18, 22, 62, 101, 20, 12, 12, 12, 13, 45, 73, 46, 44, 42, 97, 42, 32, 33, 37, 100, 100, 100, 100, 44, 93, 45, 92, 45, 91, 41, 91, 39, 91, 36, 92, 33, 35, 46, 45, 39, 37, 89, 37, 87, 38, 85, 85, 90, 23, 99, 96, 93, 93, 91, 88, 84, 34, 81, 78, 92, 98, 88, 20, 85, 14, 82, 13, 75, 40, 74, 82, 80, 97, 33, 78, 76, 67, 98, 95, 65, 65, 76, 99, 72, 70, 70, 78, 87, 55, 54, 55, 80, 47, 98, 98, 69, 12, 99, 40, 65, 67, 12, 37, 43, 46, 19, 17, 17, 39, 39, 43, 97, 26, 72, 100, 98, 14, 36, 35, 101, 70, 70, 42, 42, 43, 43, 47, 22, 27, 65, 66, 89, 88, 48, 89, 91, 27, 27, 38, 42, 28, 51, 27, 24, 24, 25, 48, 18, 18] [40, 38, 37, 41, 38, 58, 58, 29, 32, 33, 38, 37, 38, 38, 39, 57, 33, 34, 35, 32, 39, 38, 38, 39, 39, 39, 38, 38, 38, 37, 37, 40, 43, 43, 42, 42, 37, 37, 37, 32, 27, 59, 53, 58, 53, 53, 51, 47, 62, 32, 32, 32, 33, 32, 32, 32, 31, 31, 35, 36, 35, 35, 36, 33, 29, 30, 47, 25, 31, 30, 32, 31, 38, 30, 31, 25, 21, 52, 23, 23, 33, 48, 32, 32, 30, 29, 28, 49, 49, 49, 49, 42, 47, 45, 52, 43, 42, 42, 38, 37, 43, 35, 35, 44, 31, 41, 42, 35, 46, 47, 47, 48, 48, 44, 49, 48, 54, 25, 35, 44, 39, 53, 56, 47, 47, 27, 51, 31, 26, 28, 24, 28, 53, 54, 54, 54, 39, 37, 32, 32, 32, 59, 34, 34, 31, 60, 32, 59, 57, 32, 34, 36, 35, 35, 39, 39, 40, 40, 40, 40, 51, 50, 31, 29, 53, 53, 28, 27, 30, 45, 47, 47, 47, 20, 29, 51, 52, 50, 30, 27, 44, 24, 27, 30, 29, 29, 26, 48, 24, 48, 46, 47, 33, 26, 30, 32, 32, 59, 58, 55, 32, 33, 48, 33, 49, 33, 50, 34, 49, 34, 49, 34, 47, 35, 18, 36, 35, 36, 37, 63, 38, 61, 36, 59, 58, 27, 41, 56, 56, 57, 57, 57, 56, 55, 30, 54, 53, 55, 17, 56, 53, 57, 52, 58, 51, 62, 45, 63, 59, 61, 25, 38, 63, 62, 57, 60, 60, 55, 57, 58, 55, 58, 58, 57, 23, 36, 53, 53, 54, 12, 28, 23, 23, 60, 53, 23, 49, 41, 42, 29, 42, 44, 45, 46, 49, 48, 52, 52, 49, 61, 43, 56, 52, 52, 61, 58, 54, 62, 50, 53, 48, 48, 45, 45, 41, 25, 24, 41, 40, 57, 57, 23, 59, 61, 55, 55, 38, 40, 57, 41, 49, 49, 49, 49, 56, 39, 40]

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,11801.0,11786.0,11769.0,11750.0,11732.0,11713.0,11696.0,11683.0,11675.0,11670.0,...,11655.0,11651.0,11654.0,11665.0,11680.0,11698.0,11718.0,33.0,40.0,COL
1,11581.0,11588.0,11594.0,11600.0,11605.0,11608.0,11610.0,11614.0,11617.0,11622.0,...,11625.0,11629.0,11641.0,11662.0,11689.0,11720.0,11754.0,36.0,38.0,COL
2,11839.0,11818.0,11799.0,11782.0,11767.0,11754.0,11743.0,11733.0,11725.0,11718.0,...,11688.0,11688.0,11693.0,11702.0,11717.0,11737.0,11760.0,98.0,37.0,COL
3,11875.0,11848.0,11820.0,11796.0,11775.0,11756.0,11742.0,11729.0,11721.0,11715.0,...,11656.0,11662.0,11673.0,11690.0,11715.0,11746.0,11780.0,100.0,41.0,COL
4,11749.0,11736.0,11722.0,11710.0,11699.0,11689.0,11682.0,11677.0,11675.0,11675.0,...,11609.0,11606.0,11610.0,11621.0,11640.0,11666.0,11701.0,102.0,38.0,COL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,12019.0,12021.0,12025.0,12029.0,12030.0,12028.0,12025.0,12022.0,12020.0,12019.0,...,11953.0,11951.0,11954.0,11963.0,11974.0,11988.0,12004.0,24.0,49.0,COL
323,11935.0,11933.0,11935.0,11936.0,11936.0,11935.0,11933.0,11931.0,11928.0,11925.0,...,11916.0,11925.0,11940.0,11956.0,11974.0,11991.0,12009.0,25.0,49.0,COL
324,12010.0,12011.0,12011.0,12011.0,12009.0,12008.0,12006.0,12003.0,12000.0,11997.0,...,12027.0,12022.0,12025.0,12037.0,12055.0,12077.0,12100.0,48.0,56.0,COL
325,11717.0,11696.0,11676.0,11659.0,11644.0,11631.0,11622.0,11615.0,11611.0,11609.0,...,11562.0,11562.0,11567.0,11576.0,11590.0,11610.0,11633.0,18.0,39.0,COL
326,11834.0,11808.0,11784.0,11762.0,11742.0,11724.0,11708.0,11693.0,11680.0,11669.0,...,11588.0,11599.0,11614.0,11632.0,11653.0,11678.0,11704.0,18.0,40.0,COL

# NROI

In [57]:
path="../RawData/CESMZ200/2yearunnormlabeleddata/NROI"
data = np.empty(shape=(1,225))
counter = 0
for filename in os.listdir(path):
    counter+=1
    f = os.path.join(path,filename)
    newdata = pd.read_csv(f, header = None).values.reshape((1,-1))
    data = np.concatenate((data,newdata))
    data_delete = np.delete(data,0,0)
    print(filename)
    
x=[]
y=[]
for i in range(508,579,1):
    x.append(int(df.iloc[i]['225']))
    y.append(int(df.iloc[i]['226']))
print(x,y)

x_read = np.array(x)
x_read = x_read.reshape((1,-1))
y_read = np.array(y)
y_read = y_read.reshape((1,-1))

data_final = np.concatenate((data_delete, x_read.T,y_read.T), axis=1)
data_final_frame = pd.DataFrame(data_final)
data_final_frame['label'] = "NROI"
data_final_frame.to_csv('nroi2year_xy_unnormed.csv')
data_final_frame

Day168_c9_cp2_67_61.csv
Day174_c8_cp2_80_49.csv
Day182_c9_cp2_90_62.csv
Day183_c9_cp2_86_62.csv
Day186_c9_cp2_92_59.csv
Day186_c9_cp3_76_62.csv
Day216_c9_cp2_102_54.csv
Day217_c7_cp2_25_42.csv
Day220_c9_cp3_84_57.csv
Day221_c10_cp2_84_55.csv
Day221_c10_cp3_77_61.csv
Day222_c10_cp2_83_54.csv
Day222_c10_cp3_75_61.csv
Day223_c10_cp2_82_52.csv
Day223_c10_cp4_72_60.csv
Day224_c9_cp2_55_59.csv
Day225_c9_cp2_92_50.csv
Day225_c9_cp3_50_59.csv
Day226_c9_cp2_46_58.csv
Day228_c10_cp2_64_59.csv
Day228_c7_cp2_34_28.csv
Day230_c9_cp2_95_40.csv
Day230_c9_cp3_87_60.csv
Day246_c10_cp2_83_61.csv
Day247_c11_cp2_79_60.csv
Day256_c10_cp2_91_59.csv
Day272_c12_cp2_90_51.csv
Day273_c11_cp2_82_40.csv
Day284_c11_cp3_96_60.csv
Day387_c15_cp2_11_63.csv
Day422_c16_cp1_13_61.csv
Day555_c9_cp3_11_58.csv
Day556_c11_cp2_60_59.csv
Day558_c9_cp3_85_58.csv
Day559_c9_cp4_85_59.csv
Day560_c9_cp2_85_57.csv
Day560_c9_cp3_102_58.csv
Day561_c10_cp2_86_56.csv
Day561_c10_cp3_100_57.csv
Day570_c9_cp3_77_56.csv
Day574_c8_cp2_50_51.csv
Day575_c8_cp2_86_55.csv
Day577_c8_cp4_74_63.csv
Day584_c8_cp2_66_55.csv
Day584_c8_cp3_101_61.csv
Day585_c8_cp3_67_54.csv
Day586_c8_cp2_67_54.csv
Day587_c8_cp2_66_55.csv
Day593_c10_cp2_44_60.csv
Day594_c9_cp2_68_57.csv
Day595_c7_cp2_11_42.csv
Day595_c9_cp2_67_57.csv
Day596_c9_cp3_67_56.csv
Day597_c9_cp3_43_54.csv
Day610_c10_cp2_67_58.csv
Day616_c10_cp2_67_57.csv
Day617_c10_cp2_67_59.csv
Day618_c10_cp3_67_58.csv
Day620_c11_cp2_86_60.csv
Day624_c11_cp2_87_62.csv
Day631_c11_cp2_89_56.csv
Day632_c11_cp2_87_59.csv
Day633_c12_cp2_86_58.csv
Day634_c11_cp3_86_58.csv
Day636_c11_cp2_100_54.csv
Day637_c11_cp2_98_54.csv
Day638_c11_cp2_96_57.csv
Day643_c12_cp2_96_62.csv
Day646_c12_cp2_76_59.csv
Day694_c15_cp2_78_56.csv
Day694_c17_cp2_86_63.csv
[67, 80, 90, 86, 92, 76, 102, 25, 84, 84, 77, 83, 75, 82, 72, 55, 92, 50, 46, 64, 34, 95, 87, 83, 79, 91, 90, 82, 96, 11, 13, 11, 60, 85, 85, 85, 102, 86, 100, 77, 50, 86, 74, 66, 101, 67, 67, 66, 44, 68, 11, 67, 67, 43, 67, 67, 67, 67, 86, 87, 89, 87, 86, 86, 100, 98, 96, 96, 76, 78, 86] [61, 49, 62, 62, 59, 62, 54, 42, 57, 55, 61, 54, 61, 52, 60, 59, 50, 59, 58, 59, 28, 40, 60, 61, 60, 59, 51, 40, 60, 63, 61, 58, 59, 58, 59, 57, 58, 56, 57, 56, 51, 55, 63, 55, 61, 54, 54, 55, 60, 57, 42, 57, 56, 54, 58, 57, 59, 58, 60, 62, 56, 59, 58, 58, 54, 54, 57, 62, 59, 56, 63]

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,12379.0,12384.0,12388.0,12393.0,12400.0,12405.0,12409.0,12411.0,12414.0,12416.0,...,12400.0,12401.0,12405.0,12413.0,12417.0,12427.0,12434.0,67.0,61.0,NROI
1,12348.0,12355.0,12364.0,12370.0,12375.0,12381.0,12384.0,12384.0,12384.0,12382.0,...,12379.0,12376.0,12371.0,12373.0,12373.0,12374.0,12374.0,80.0,49.0,NROI
2,12478.0,12477.0,12473.0,12465.0,12455.0,12445.0,12436.0,12429.0,12425.0,12423.0,...,12399.0,12396.0,12405.0,12411.0,12413.0,12413.0,12415.0,90.0,62.0,NROI
3,12483.0,12483.0,12482.0,12477.0,12469.0,12459.0,12447.0,12438.0,12431.0,12427.0,...,12408.0,12410.0,12417.0,12426.0,12427.0,12428.0,12431.0,86.0,62.0,NROI
4,12434.0,12434.0,12434.0,12433.0,12432.0,12432.0,12431.0,12429.0,12427.0,12425.0,...,12406.0,12402.0,12400.0,12402.0,12404.0,12408.0,12413.0,92.0,59.0,NROI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12356.0,12352.0,12348.0,12351.0,12362.0,12367.0,12369.0,96.0,57.0,NROI
67,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12422.0,12417.0,12413.0,12411.0,12412.0,12413.0,12415.0,96.0,62.0,NROI
68,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12403.0,12402.0,12404.0,12404.0,12406.0,12402.0,12404.0,76.0,59.0,NROI
69,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12332.0,12339.0,12348.0,12357.0,12366.0,12375.0,12391.0,78.0,56.0,NROI
70,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12429.0,12430.0,12428.0,12426.0,12423.0,12419.0,12413.0,86.0,63.0,NROI

# COH

In [58]:
path="../RawData/CESMZ200/2yearunnormlabeleddata/COH"
data = np.empty(shape=(1,225))
counter = 0
for filename in os.listdir(path):
    counter+=1
    f = os.path.join(path,filename)
    newdata = pd.read_csv(f, header = None).values.reshape((1,-1))
    data = np.concatenate((data,newdata))
    data_delete = np.delete(data,0,0)
    print(filename)
    
x=[]
y=[]
for i in range(580,len(df),1):
    x.append(int(df.iloc[i]['225']))
    y.append(int(df.iloc[i]['226']))
print(x,y)

x_read = np.array(x)
x_read = x_read.reshape((1,-1))
y_read = np.array(y)
y_read = y_read.reshape((1,-1))

data_final = np.concatenate((data_delete, x_read.T,y_read.T), axis=1)
data_final_frame = pd.DataFrame(data_final)
data_final_frame['label'] = "COH"
data_final_frame.to_csv('coh2year_xy_unnormed.csv')
data_final_frame

Day115_c11_cp1_101_22.csv
Day127_c7_cp1_95_19.csv
Day128_c7_cp1_73_27.csv
Day129_c8_cp1_63_27.csv
Day143_c7_cp1_86_23.csv
Day145_c7_cp1_85_22.csv
Day147_c10_cp1_11_33.csv
Day150_c8_cp1_31_20.csv
Day153_c8_cp1_33_18.csv
Day155_c8_cp1_28_13.csv
Day156_c7_cp1_32_13.csv
Day158_c7_cp1_21_14.csv
Day161_c6_cp1_58_22.csv
Day171_c5_cp1_96_15.csv
Day172_c10_cp1_32_42.csv
Day173_c9_cp1_34_44.csv
Day184_c11_cp1_46_59.csv
Day185_c11_cp1_44_58.csv
Day185_c8_cp1_12_20.csv
Day186_c11_cp1_41_57.csv
Day186_c8_cp1_16_15.csv
Day188_c8_cp1_25_19.csv
Day195_c8_cp1_23_12.csv
Day196_c7_cp1_31_14.csv
Day197_c7_cp1_37_19.csv
Day198_c10_cp1_59_56.csv
Day198_c7_cp1_39_24.csv
Day199_c7_cp1_39_26.csv
Day1_c6_cp1_102_14.csv
Day202_c11_cp1_56_52.csv
Day204_c8_cp4_67_54.csv
Day205_c6_cp1_36_19.csv
Day206_c7_cp1_35_17.csv
Day206_c9_cp2_73_56.csv
Day207_c6_cp1_35_18.csv
Day210_c6_cp1_44_17.csv
Day211_c8_cp1_17_30.csv
Day212_c8_cp1_18_32.csv
Day214_c11_cp1_42_58.csv
Day215_c11_cp1_35_59.csv
Day218_c6_cp1_61_16.csv
Day21_c8_cp1_44_12.csv
Day221_c12_cp1_51_55.csv
Day227_c12_cp1_54_56.csv
Day229_c11_cp1_35_59.csv
Day230_c7_cp1_55_12.csv
Day233_c11_cp1_92_44.csv
Day235_c12_cp1_54_53.csv
Day238_c12_cp2_81_61.csv
Day238_c12_cp3_91_61.csv
Day239_c12_cp1_45_57.csv
Day239_c12_cp2_75_61.csv
Day240_c12_cp1_48_53.csv
Day241_c12_cp1_51_51.csv
Day241_c12_cp2_67_63.csv
Day243_c12_cp1_59_48.csv
Day243_c12_cp4_32_62.csv
Day244_c12_cp3_60_62.csv
Day245_c7_cp1_84_21.csv
Day246_c12_cp1_63_49.csv
Day247_c13_cp1_66_47.csv
Day249_c13_cp1_68_48.csv
Day250_c12_cp1_67_48.csv
Day251_c11_cp2_67_49.csv
Day254_c12_cp1_66_59.csv
Day255_c12_cp1_59_62.csv
Day256_c12_cp1_59_63.csv
Day259_c13_cp3_54_63.csv
Day260_c13_cp3_57_62.csv
Day261_c10_cp1_59_18.csv
Day265_c14_cp2_60_63.csv
Day270_c14_cp1_61_63.csv
Day277_c13_cp1_48_27.csv
Day278_c13_cp1_58_33.csv
Day297_c16_cp1_75_63.csv
Day298_c13_cp1_51_31.csv
Day2_c7_cp1_98_16.csv
Day313_c7_cp1_85_16.csv
Day320_c11_cp1_28_19.csv
Day321_c10_cp1_36_19.csv
Day35_c11_cp1_19_20.csv
Day385_c15_cp2_42_58.csv
Day394_c4_cp3_95_13.csv
Day434_c8_cp1_76_21.csv
Day445_c11_cp1_20_17.csv
Day449_c9_cp1_38_17.csv
Day463_c10_cp1_70_20.csv
Day472_c10_cp1_25_13.csv
Day473_c10_cp1_29_13.csv
Day474_c10_cp1_31_13.csv
Day475_c8_cp1_32_15.csv
Day476_c8_cp1_31_20.csv
Day528_c6_cp1_84_11.csv
Day544_c8_cp1_36_19.csv
Day545_c8_cp1_39_17.csv
Day546_c8_cp1_40_19.csv
Day548_c5_cp2_37_37.csv
Day549_c11_cp1_73_51.csv
Day549_c8_cp1_33_16.csv
Day550_c8_cp1_36_17.csv
Day551_c11_cp1_89_49.csv
Day551_c8_cp1_41_22.csv
Day552_c11_cp3_87_51.csv
Day552_c8_cp1_43_24.csv
Day553_c11_cp1_78_48.csv
Day553_c8_cp2_49_25.csv
Day554_c11_cp1_85_50.csv
Day558_c11_cp1_62_49.csv
Day559_c11_cp1_63_47.csv
Day564_c12_cp2_73_59.csv
Day569_c11_cp2_71_44.csv
Day569_c11_cp3_52_48.csv
Day572_c11_cp1_11_40.csv
Day577_c10_cp1_60_40.csv
Day577_c10_cp2_74_47.csv
Day578_c10_cp1_71_45.csv
Day581_c10_cp1_76_47.csv
Day582_c11_cp1_77_47.csv
Day583_c11_cp2_82_49.csv
Day583_c9_cp3_13_38.csv
Day585_c8_cp2_16_36.csv
Day593_c10_cp1_52_50.csv
Day594_c10_cp1_24_31.csv
Day594_c11_cp1_52_49.csv
Day595_c10_cp1_31_32.csv
Day598_c11_cp1_72_56.csv
Day599_c12_cp1_101_63.csv
Day600_c12_cp1_66_63.csv
Day601_c12_cp3_93_62.csv
Day606_c12_cp3_43_63.csv
Day607_c12_cp2_61_61.csv
Day608_c12_cp4_59_61.csv
Day609_c11_cp2_45_59.csv
Day611_c10_cp1_19_43.csv
Day616_c11_cp1_43_38.csv
Day617_c11_cp1_49_37.csv
Day618_c12_cp1_31_62.csv
Day620_c13_cp1_51_56.csv
Day621_c12_cp2_102_48.csv
Day621_c13_cp1_50_54.csv
Day622_c13_cp1_51_52.csv
Day623_c13_cp1_54_51.csv
Day624_c13_cp1_55_53.csv
Day627_c13_cp1_80_56.csv
Day628_c13_cp1_76_56.csv
Day631_c13_cp2_70_63.csv
Day635_c11_cp1_43_31.csv
Day645_c14_cp1_56_63.csv
Day652_c15_cp1_23_49.csv
Day656_c14_cp2_83_63.csv
Day662_c15_cp2_60_63.csv
Day664_c11_cp1_48_28.csv
Day666_c16_cp1_66_63.csv
Day673_c16_cp1_75_63.csv
Day676_c17_cp1_73_61.csv
Day677_c17_cp1_74_59.csv
Day696_c17_cp2_91_53.csv
Day70_c16_cp1_27_31.csv
Day71_c16_cp1_28_37.csv
Day730_c12_cp1_24_28.csv
Day731_c12_cp1_24_27.csv
[101, 95, 73, 63, 86, 85, 11, 31, 33, 28, 32, 21, 58, 96, 32, 34, 46, 44, 12, 41, 16, 25, 23, 31, 37, 59, 39, 39, 2, 56, 67, 36, 35, 73, 35, 44, 17, 18, 42, 35, 61, 44, 51, 54, 35, 55, 92, 54, 81, 91, 45, 75, 48, 51, 67, 59, 32, 60, 84, 63, 66, 68, 67, 67, 66, 59, 59, 54, 57, 59, 60, 61, 48, 58, 75, 51, 98, 85, 28, 36, 19, 42, 95, 76, 20, 38, 70, 25, 29, 31, 32, 31, 84, 36, 39, 40, 37, 73, 33, 36, 89, 41, 87, 43, 78, 49, 85, 62, 63, 73, 71, 52, 11, 60, 74, 71, 76, 77, 82, 13, 16, 52, 24, 52, 31, 72, 1, 66, 93, 43, 61, 59, 45, 19, 43, 49, 31, 51, 102, 50, 51, 54, 55, 80, 76, 70, 43, 56, 23, 83, 60, 48, 66, 75, 73, 74, 91, 27, 28, 24, 24] [22, 19, 27, 27, 23, 22, 33, 20, 18, 13, 13, 14, 22, 15, 42, 44, 59, 58, 20, 57, 15, 19, 12, 14, 19, 56, 24, 26, 14, 52, 54, 19, 17, 56, 18, 17, 30, 32, 58, 59, 16, 12, 55, 56, 59, 12, 44, 53, 61, 61, 57, 61, 53, 51, 63, 48, 62, 62, 21, 49, 47, 48, 48, 49, 59, 62, 63, 63, 62, 18, 63, 63, 27, 33, 63, 31, 16, 16, 19, 19, 20, 58, 13, 21, 17, 17, 20, 13, 13, 13, 15, 20, 11, 19, 17, 19, 37, 51, 16, 17, 49, 22, 51, 24, 48, 25, 50, 49, 47, 59, 44, 48, 40, 40, 47, 45, 47, 47, 49, 38, 36, 50, 31, 49, 32, 56, 63, 63, 62, 63, 61, 61, 59, 43, 38, 37, 62, 56, 48, 54, 52, 51, 53, 56, 56, 63, 31, 63, 49, 63, 63, 28, 63, 63, 61, 59, 53, 31, 37, 28, 27]

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,11540.0,11548.0,11557.0,11566.0,11574.0,11580.0,11588.0,11594.0,11600.0,11606.0,...,11728.0,11725.0,11723.0,11723.0,11725.0,11729.0,11734.0,101.0,22.0,COH
1,11774.0,11786.0,11799.0,11813.0,11825.0,11836.0,11845.0,11853.0,11859.0,11864.0,...,11888.0,11888.0,11889.0,11889.0,11889.0,11887.0,11885.0,95.0,19.0,COH
2,11747.0,11749.0,11752.0,11754.0,11758.0,11761.0,11764.0,11767.0,11770.0,11773.0,...,11872.0,11879.0,11886.0,11890.0,11890.0,11888.0,11884.0,73.0,27.0,COH
3,11801.0,11804.0,11806.0,11806.0,11806.0,11803.0,11800.0,11795.0,11789.0,11782.0,...,11890.0,11886.0,11881.0,11875.0,11870.0,11863.0,11858.0,63.0,27.0,COH
4,11803.0,11825.0,11846.0,11864.0,11880.0,11894.0,11906.0,11915.0,11921.0,11924.0,...,11984.0,11969.0,11949.0,11925.0,11896.0,11866.0,11837.0,86.0,23.0,COH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,12253.0,12249.0,12244.0,12238.0,12231.0,12224.0,12217.0,12209.0,12202.0,12194.0,...,12305.0,12304.0,12305.0,12303.0,12300.0,12293.0,12278.0,91.0,53.0,COH
157,11868.0,11896.0,11923.0,11947.0,11971.0,11991.0,12008.0,12024.0,12036.0,12045.0,...,12070.0,12061.0,12053.0,12045.0,12038.0,12030.0,12022.0,27.0,31.0,COH
158,11956.0,11959.0,11962.0,11965.0,11966.0,11967.0,11968.0,11967.0,11966.0,11964.0,...,12012.0,12014.0,12020.0,12026.0,12032.0,12037.0,12040.0,28.0,37.0,COH
159,11617.0,11635.0,11650.0,11665.0,11677.0,11686.0,11699.0,11705.0,11710.0,11714.0,...,11796.0,11794.0,11787.0,11777.0,11763.0,11744.0,11721.0,24.0,28.0,COH
160,11657.0,11673.0,11687.0,11700.0,11709.0,11715.0,11722.0,11725.0,11725.0,11725.0,...,11784.0,11788.0,11789.0,11787.0,11782.0,11774.0,11763.0,24.0,27.0,COH

# concat all

In [64]:
cl = pd.read_csv('cl2year_xy_unnormed.csv',index_col = 0)
col = pd.read_csv('col2year_xy_unnormed.csv',index_col = 0)
coh = pd.read_csv('coh2year_xy_unnormed.csv',index_col = 0)
nroi = pd.read_csv('nroi2year_xy_unnormed.csv',index_col = 0)
data_all = pd.concat([cl,col,coh,nroi], ignore_index = True)

In [65]:
data_all

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11043.0,11038.0,11036.0,11040.0,11046.0,11056.0,11073.0,94.0,17.0,CL
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11593.0,11592.0,11594.0,11598.0,11604.0,11613.0,11626.0,100.0,32.0,CL
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11257.0,11254.0,11258.0,11268.0,11284.0,11306.0,11336.0,31.0,29.0,CL
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11257.0,11254.0,11258.0,11268.0,11284.0,11306.0,11336.0,31.0,29.0,CL
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11253.0,11253.0,11257.0,11266.0,11279.0,11296.0,11318.0,31.0,28.0,CL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12356.0,12352.0,12348.0,12351.0,12362.0,12367.0,12369.0,96.0,57.0,NROI
733,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12422.0,12417.0,12413.0,12411.0,12412.0,12413.0,12415.0,96.0,62.0,NROI
734,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12403.0,12402.0,12404.0,12404.0,12406.0,12402.0,12404.0,76.0,59.0,NROI
735,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12332.0,12339.0,12348.0,12357.0,12366.0,12375.0,12391.0,78.0,56.0,NROI
736,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12429.0,12430.0,12428.0,12426.0,12423.0,12419.0,12413.0,86.0,63.0,NROI

In [66]:
data_all.to_csv('year2_xy_unnormed.csv')

# map X and Y

In [33]:
data =  pd.read_csv('../RawData/ROI_Pressure/Unnormed/year2_xy_unnormed.csv',index_col=0)
data

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,label
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11043.0,11038.0,11036.0,11040.0,11046.0,11056.0,11073.0,94.0,17.0,CL
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11593.0,11592.0,11594.0,11598.0,11604.0,11613.0,11626.0,100.0,32.0,CL
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11257.0,11254.0,11258.0,11268.0,11284.0,11306.0,11336.0,31.0,29.0,CL
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11257.0,11254.0,11258.0,11268.0,11284.0,11306.0,11336.0,31.0,29.0,CL
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11253.0,11253.0,11257.0,11266.0,11279.0,11296.0,11318.0,31.0,28.0,CL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12356.0,12352.0,12348.0,12351.0,12362.0,12367.0,12369.0,96.0,57.0,NROI
733,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12422.0,12417.0,12413.0,12411.0,12412.0,12413.0,12415.0,96.0,62.0,NROI
734,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12403.0,12402.0,12404.0,12404.0,12406.0,12402.0,12404.0,76.0,59.0,NROI
735,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12332.0,12339.0,12348.0,12357.0,12366.0,12375.0,12391.0,78.0,56.0,NROI
736,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12429.0,12430.0,12428.0,12426.0,12423.0,12419.0,12413.0,86.0,63.0,NROI

In [34]:
x = data.iloc[:,225]
y = data.iloc[:,226]

In [35]:
print(x.max())
print(x.min())
print(y.max())
print(y.min())

102.0
1.0
63.0
11.0

In [36]:
normalized_x = (x-x.min())/(x.max()-x.min())
normalized_y = (y-y.min())/(y.max()-y.min())

In [37]:
first = np.where(normalized_x >= 0.5,1,0)

In [38]:
df = pd.DataFrame(first,columns=['first'])

In [39]:
def sec(num):
    if num >= 0.25 and num < 0.5:
        return 1
    if num >= 0.75 and num <= 1:
        return 1
    else:
        return 0

In [40]:
df['second'] = normalized_x.apply(lambda x: sec(x))

In [41]:
thr = np.where(normalized_y>=0.5,1,0)
df['thrid']=thr

In [42]:
df['Forth'] = normalized_y.apply(lambda x: sec(x))

In [43]:
df

     first  second  thrid  Forth
0        1       1      0      0
1        1       1      0      1
2        0       1      0      1
3        0       1      0      1
4        0       1      0      1
..     ...     ...    ...    ...
732      1       1      1      1
733      1       1      1      1
734      1       0      1      1
735      1       1      1      1
736      1       1      1      1

[737 rows x 4 columns]

In [44]:
normalized_x[1]

0.9801980198019802

In [45]:
normalized_y[1]

0.40384615384615385

In [57]:
temp = pd.concat([data,df],axis=1)
temp

,0,1,2,3,4,5,6,7,8,9,...,222,223,224,225,226,label,first,second,thrid,Forth
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11046.0,11056.0,11073.0,94.0,17.0,CL,1,1,0,0
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11604.0,11613.0,11626.0,100.0,32.0,CL,1,1,0,1
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11284.0,11306.0,11336.0,31.0,29.0,CL,0,1,0,1
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11284.0,11306.0,11336.0,31.0,29.0,CL,0,1,0,1
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11279.0,11296.0,11318.0,31.0,28.0,CL,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12362.0,12367.0,12369.0,96.0,57.0,NROI,1,1,1,1
733,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12412.0,12413.0,12415.0,96.0,62.0,NROI,1,1,1,1
734,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12406.0,12402.0,12404.0,76.0,59.0,NROI,1,0,1,1
735,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12366.0,12375.0,12391.0,78.0,56.0,NROI,1,1,1,1
736,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12423.0,12419.0,12413.0,86.0,63.0,NROI,1,1,1,1

In [58]:
temp.to_csv('year2map.csv')

# prepare datas into different normalization methods.

In [13]:
data =  pd.read_csv('../RawData/ROI_Pressure/Unnormed/year2_xy_map_unnormed.csv',index_col=0)
data

,0,1,2,3,4,5,6,7,8,9,...,222,223,224,225,226,first,second,thrid,Forth,label
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11046.0,11056.0,11073.0,94.0,17.0,1,1,0,0,CL
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11604.0,11613.0,11626.0,100.0,32.0,1,1,0,1,CL
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11284.0,11306.0,11336.0,31.0,29.0,0,1,0,1,CL
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11284.0,11306.0,11336.0,31.0,29.0,0,1,0,1,CL
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11279.0,11296.0,11318.0,31.0,28.0,0,1,0,1,CL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12362.0,12367.0,12369.0,96.0,57.0,1,1,1,1,NROI
733,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12412.0,12413.0,12415.0,96.0,62.0,1,1,1,1,NROI
734,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12406.0,12402.0,12404.0,76.0,59.0,1,0,1,1,NROI
735,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12366.0,12375.0,12391.0,78.0,56.0,1,1,1,1,NROI
736,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12423.0,12419.0,12413.0,86.0,63.0,1,1,1,1,NROI

In [14]:
X_train = data.iloc[:,:231]

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [17]:
X_train_df = pd.DataFrame(X_train)
X_train_df

,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
0,-1.965489,-1.952570,-1.942915,-1.932458,-1.921184,-1.912234,-1.903198,-1.895981,-1.887033,-1.880628,...,-2.009244,-2.021022,-2.030776,-2.030810,1.207321,-1.316900,0.835558,0.773756,-1.028912,-1.086496
1,-0.679044,-0.679129,-0.681179,-0.683338,-0.688237,-0.693714,-0.697965,-0.707804,-0.717113,-0.728046,...,-0.785845,-0.793601,-0.799377,-0.799903,1.422715,-0.368907,0.835558,0.773756,-1.028912,0.920390
2,-1.548455,-1.554620,-1.556479,-1.554709,-1.551762,-1.548290,-1.542088,-1.532863,-1.523875,-1.512538,...,-1.509360,-1.497498,-1.478083,-1.445406,-1.054323,-0.558505,-1.196805,0.773756,-1.028912,0.920390
3,-1.548455,-1.554620,-1.556479,-1.554709,-1.551762,-1.548290,-1.542088,-1.532863,-1.523875,-1.512538,...,-1.509360,-1.497498,-1.478083,-1.445406,-1.054323,-0.558505,-1.196805,0.773756,-1.028912,0.920390
4,-1.376457,-1.397780,-1.412148,-1.422613,-1.427082,-1.433118,-1.436285,-1.434040,-1.434235,-1.429718,...,-1.513745,-1.508497,-1.500191,-1.485472,-1.054323,-0.621705,-1.196805,0.773756,-1.028912,0.920390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,0.734632,0.779241,0.836629,0.887911,0.904897,0.914088,0.909780,0.900947,0.882621,0.850141,...,0.865086,0.873756,0.867542,0.853919,1.279119,1.211081,0.835558,0.773756,0.971901,0.920390
733,0.993806,1.001625,1.029847,1.052452,1.061901,1.075329,1.082284,1.087103,1.089483,1.089400,...,0.996634,0.983740,0.969238,0.956309,1.279119,1.527079,0.835558,0.773756,0.971901,0.920390
734,1.064490,1.069510,1.060110,1.059404,1.057283,1.052294,1.052384,1.048033,1.050409,1.064093,...,0.981287,0.970542,0.944919,0.931825,0.561137,1.337480,0.835558,-1.292397,0.971901,0.920390
735,0.826521,0.847127,0.864564,0.878641,0.884117,0.886446,0.884479,0.877965,0.871129,0.859343,...,0.878241,0.882555,0.885228,0.902888,0.632935,1.147882,0.835558,0.773756,0.971901,0.920390
736,0.777042,0.804991,0.843613,0.853149,0.842557,0.808129,0.829277,0.845790,0.878024,0.914557,...,1.029521,1.007937,0.982502,0.951858,0.920128,1.590278,0.835558,0.773756,0.971901,0.920390

In [18]:
X_train_df.to_csv("year2_xy_map_standard.csv")

In [4]:
data =  pd.read_csv('../RawData/ROI_Pressure/Unnormed/year2_xy_map_unnormed.csv',index_col=0)
data

,0,1,2,3,4,5,6,7,8,9,...,222,223,224,225,226,first,second,thrid,Forth,label
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11046.0,11056.0,11073.0,94.0,17.0,1,1,0,0,CL
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11604.0,11613.0,11626.0,100.0,32.0,1,1,0,1,CL
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11284.0,11306.0,11336.0,31.0,29.0,0,1,0,1,CL
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11284.0,11306.0,11336.0,31.0,29.0,0,1,0,1,CL
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11279.0,11296.0,11318.0,31.0,28.0,0,1,0,1,CL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12362.0,12367.0,12369.0,96.0,57.0,1,1,1,1,NROI
733,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12412.0,12413.0,12415.0,96.0,62.0,1,1,1,1,NROI
734,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12406.0,12402.0,12404.0,76.0,59.0,1,0,1,1,NROI
735,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12366.0,12375.0,12391.0,78.0,56.0,1,1,1,1,NROI
736,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12423.0,12419.0,12413.0,86.0,63.0,1,1,1,1,NROI

In [7]:
data_x = data.iloc[:,:231]
data_x

,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,first,second,thrid,Forth
0,11133.0,11132.0,11130.0,11129.0,11129.0,11129.0,11130.0,11131.0,11134.0,11137.0,...,11040.0,11046.0,11056.0,11073.0,94.0,17.0,1,1,0,0
1,11679.0,11676.0,11672.0,11668.0,11663.0,11658.0,11654.0,11648.0,11643.0,11638.0,...,11598.0,11604.0,11613.0,11626.0,100.0,32.0,1,1,0,1
2,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11268.0,11284.0,11306.0,11336.0,31.0,29.0,0,1,0,1
3,11310.0,11302.0,11296.0,11292.0,11289.0,11287.0,11287.0,11289.0,11292.0,11297.0,...,11268.0,11284.0,11306.0,11336.0,31.0,29.0,0,1,0,1
4,11383.0,11369.0,11358.0,11349.0,11343.0,11337.0,11333.0,11332.0,11331.0,11333.0,...,11266.0,11279.0,11296.0,11318.0,31.0,28.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,12279.0,12299.0,12324.0,12346.0,12353.0,12356.0,12353.0,12348.0,12339.0,12324.0,...,12351.0,12362.0,12367.0,12369.0,96.0,57.0,1,1,1,1
733,12389.0,12394.0,12407.0,12417.0,12421.0,12426.0,12428.0,12429.0,12429.0,12428.0,...,12411.0,12412.0,12413.0,12415.0,96.0,62.0,1,1,1,1
734,12419.0,12423.0,12420.0,12420.0,12419.0,12416.0,12415.0,12412.0,12412.0,12417.0,...,12404.0,12406.0,12402.0,12404.0,76.0,59.0,1,0,1,1
735,12318.0,12328.0,12336.0,12342.0,12344.0,12344.0,12342.0,12338.0,12334.0,12328.0,...,12357.0,12366.0,12375.0,12391.0,78.0,56.0,1,1,1,1
736,12297.0,12310.0,12327.0,12331.0,12326.0,12310.0,12318.0,12324.0,12337.0,12352.0,...,12426.0,12423.0,12419.0,12413.0,86.0,63.0,1,1,1,1

In [9]:
from sklearn.preprocessing import MinMaxScaler #normalisation

def minmax_scaler(data):
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(data)
    return scaled
train_x_norm = minmax_scaler(data_x)
data_x_norm = pd.DataFrame(train_x_norm)

In [10]:
data_x_norm

,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
0,0.266183,0.267322,0.267839,0.268356,0.269669,0.271125,0.272727,0.274101,0.276006,0.277690,...,0.238537,0.240021,0.241253,0.244748,0.920792,0.115385,1.0,1.0,0.0,0.0
1,0.548938,0.548604,0.548087,0.547053,0.546066,0.545360,0.544935,0.543512,0.542081,0.540682,...,0.526018,0.529290,0.532115,0.535189,0.980198,0.403846,1.0,1.0,0.0,1.0
2,0.357846,0.355222,0.353671,0.352637,0.352484,0.353033,0.354286,0.356436,0.358599,0.361680,...,0.356002,0.363401,0.371802,0.382878,0.297030,0.346154,0.0,1.0,0.0,1.0
3,0.357846,0.355222,0.353671,0.352637,0.352484,0.353033,0.354286,0.356436,0.358599,0.361680,...,0.356002,0.363401,0.371802,0.382878,0.297030,0.346154,0.0,1.0,0.0,1.0
4,0.395650,0.389866,0.385729,0.382110,0.380435,0.378953,0.378182,0.378843,0.378986,0.380577,...,0.354972,0.360809,0.366580,0.373424,0.297030,0.326923,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,0.859658,0.870734,0.885212,0.897622,0.903209,0.907206,0.908052,0.908286,0.905907,0.900787,...,0.913962,0.922240,0.925849,0.925420,0.940594,0.884615,1.0,1.0,1.0,1.0
733,0.916624,0.919855,0.928128,0.934333,0.938406,0.943494,0.947013,0.950495,0.952953,0.955381,...,0.944874,0.948160,0.949869,0.949580,0.940594,0.980769,1.0,1.0,1.0,1.0
734,0.932160,0.934850,0.934850,0.935884,0.937371,0.938310,0.940260,0.941636,0.944067,0.949606,...,0.941267,0.945049,0.944125,0.943803,0.742574,0.923077,1.0,0.0,1.0,1.0
735,0.879855,0.885729,0.891417,0.895553,0.898551,0.900985,0.902338,0.903075,0.903293,0.902887,...,0.917053,0.924313,0.930026,0.936975,0.762376,0.865385,1.0,1.0,1.0,1.0
736,0.868980,0.876422,0.886763,0.889866,0.889234,0.883359,0.889870,0.895779,0.904861,0.915486,...,0.952602,0.953862,0.953003,0.948529,0.841584,1.000000,1.0,1.0,1.0,1.0

In [12]:
data_x_norm.to_csv('year2_xy_map_minmax.csv') # D:\ClimateChange\RawData\ROI_Pressure\MinMax\cutfirst

# norm then cut

In [6]:
#D:\ClimateChange\RawData\CESMZ200\reverse_csv
from sklearn.preprocessing import MinMaxScaler #normalisation

def minmax_scaler(data):
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(data)
    return scaled

In [17]:
path = "../RawData/CESMZ200/reverse_csv"
for file in os.listdir(path):
    data = pd.read_csv(file)
    pd.DataFrame(minmax_scaler(data)).to_csv(file) # normalisation

FileNotFoundError: [Errno 2] No such file or directory: 'day1.csv'

In [5]:
data = pd.read_csv("../RawData/CESMZ200/reverse_csv/day1.csv",header = None)
data

,0,1,2,3,4,5,6,7,8,9,...,103,104,105,106,107,108,109,110,111,112
0,10875,10872,10869,10866,10863,10861,10858,10856,10853,10851,...,11023,11022,11020,11019,11017,11015,11013,11010,11009,11006
1,10892,10889,10885,10882,10879,10876,10873,10870,10868,10865,...,11041,11040,11038,11036,11034,11032,11029,11027,11024,11022
2,10907,10903,10900,10897,10894,10890,10887,10884,10881,10878,...,11059,11057,11055,11053,11051,11048,11046,11043,11040,11037
3,10920,10917,10913,10910,10907,10903,10900,10897,10894,10891,...,11081,11079,11076,11073,11071,11068,11065,11063,11059,11056
4,10930,10927,10924,10920,10917,10914,10911,10908,10905,10902,...,11102,11100,11099,11096,11093,11090,11086,11082,11079,11075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,12321,12314,12307,12303,12303,12305,12310,12318,12326,12335,...,12353,12350,12346,12341,12337,12334,12330,12327,12324,12321
70,12325,12318,12312,12307,12308,12310,12315,12324,12334,12343,...,12362,12359,12356,12352,12348,12345,12342,12339,12336,12333
71,12332,12325,12319,12315,12316,12318,12323,12332,12342,12352,...,12369,12366,12363,12360,12357,12354,12351,12348,12345,12343
72,12340,12334,12327,12324,12325,12328,12334,12342,12351,12360,...,12372,12371,12368,12366,12363,12360,12357,12354,12352,12350
73,12349,12344,12337,12335,12335,12338,12344,12351,12360,12369,...,12375,12373,12372,12369,12367,12364,12361,12358,12356,12354

In [15]:
pd.DataFrame(minmax_scaler(data)).to_csv("test.csv") # normalisation

In [16]:
pd.DataFrame(minmax_scaler(data)).to_csv(file)